### ISSUE TITLE
Stackfiles.io stack file for deployment with tutumcloud/haproxy?

### ISSUE THREAD

**Issue by danielloader** [Levino/letsencrypt-cert-service#13]
Any chance of a sample stack file for putting the two services together and added to [stackfiles.io](https://stackfiles.io/)?

Would be beneficial as a simple template to start from to trial it.

If not added to stackfiles.io maybe an example docker-cloud.yml in the repo?

**Comment by levino** [comment]
Yes. Should be done.

**Comment by levino** [comment]
Here you are my dear: https://stackfiles.io/registry/574723f10a1bcb01008848ac
